const data=window.FERVAL_DATA,grid=document.querySelector('#productGrid'),individualGrid=document.querySelector('#individualGrid');
function cardTemplate(p,i){return `<article class="product-card" data-index="${i}" tabindex="0"><img src="${p.image}" alt="${p.title}" loading="lazy"><div class="product-card__content"><span class="product-card__tag">${p.tag}</span><h3>${p.title}</h3><div class="product-card__bottom"><p>${p.short}</p><span class="price">${p.price}</span></div></div></article>`}
grid.innerHTML=data.products.map(cardTemplate).join('');individualGrid.innerHTML=data.individuals.map(([n,p])=>`<div class="individual-item"><span>${n}</span><strong>${p}</strong></div>`).join('');
const modal=document.querySelector('#modal'),modalImg=document.querySelector('#modalImg'),modalTag=document.querySelector('#modalTag'),modalTitle=document.querySelector('#modalTitle'),modalText=document.querySelector('#modalText'),modalIncludes=document.querySelector('#modalIncludes'),modalPrice=document.querySelector('#modalPrice');
function openModal(i){const p=data.products[i];modalImg.src=p.image;modalImg.alt=p.title;modalTag.textContent=p.tag;modalTitle.textContent=p.title;modalText.textContent=p.text;modalIncludes.textContent=p.includes;modalPrice.textContent=p.price;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('.product-card').forEach(c=>{c.addEventListener('click',()=>openModal(c.dataset.index));c.addEventListener('keydown',e=>{if(e.key==='Enter')openModal(c.dataset.index)})});document.querySelector('.modal__close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const navToggle=document.querySelector('.nav__toggle'),navLinks=document.querySelector('.nav__links');navToggle.addEventListener('click',()=>navLinks.classList.toggle('open'));navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));
const w=document.querySelector('#whatsappBtn');const msg=encodeURIComponent('Hola Ferval, quiero hacer un pedido de la colección Donde viven los recuerdos 2026. ¿Me ayudas a confirmar disponibilidad, personalización y entrega?');w.href=`https://wa.me/${data.whatsapp}?text=${msg}`;
const musicToggle=document.querySelector('#musicToggle');if(musicToggle)musicToggle.addEventListener('click',()=>alert('La música se habilitará cuando agreguemos una pista autorizada.'));
